export default {
	SET_CURRENTLY: 'SET_CURRENTLY',
	SET_DAILY: 'SET_DAILY',
	SET_HOURLY: 'SET_HOURLY',
	SET_TIMEZONE: 'SET_TIMEZONE',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
	SET_GEOLOCATION_ACTIVE: 'SET_GEOLOCATION_ACTIVE',
	SET_LOCATION_RESULTS: 'SET_LOCATION_RESULTS'
};
