export default {
	SET_CURRENTLY: 'weather/SET_CURRENTLY',
	SET_DAILY: 'weather/SET_DAILY',
	SET_HOURLY: 'weather/SET_HOURLY',
	SET_TIMEZONE: 'weather/SET_TIMEZONE',
	SET_LOADING: 'weather/SET_LOADING',
	SET_ERROR: 'weather/SET_ERROR',
	SET_GEOLOCATION_ACTIVE: 'weather/SET_GEOLOCATION_ACTIVE',
	SET_LOCATION_RESULTS: 'weather/SET_LOCATION_RESULTS',
	SET_STORAGE_LOCATIONS: 'storage/SET_STORAGE_LOCATION'
};
